# Generated by Django 3.2.7 on 2021-10-15 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Camiseta', 'Camiseta'), ('Medias', 'Medias'), ('Calzonas', 'Calzonas'), ('Sudaderas', 'Sudaderas')], max_length=100)),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_stock', models.CharField(default='e0001', max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FooGearApp.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('clave', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2021, 10, 15, 19, 55, 6, 742261, tzinfo=utc), null=True, verbose_name='Fecha Reserva')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FooGearApp.comprador')),
                ('producto', models.ManyToManyField(to='FooGearApp.Producto')),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FooGearApp.tienda')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FooGearApp.stock'),
        ),
    ]
