# Generated by Django 3.2.7 on 2021-10-10 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idstock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='idstock',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='idReserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 15, 7, 23, 17850, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Camiseta', 'Camiseta'), ('Medias', 'Medias'), ('Calzonas', 'Calzonas'), ('Sudaderas', 'Sudaderas')], max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FooGearApp.tienda'),
        ),
        migrations.AddField(
            model_name='stock',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FooGearApp.tienda'),
        ),
    ]
