# Generated by Django 3.2.7 on 2021-10-18 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='clave',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 11, 42, 7, 391651, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
