# Generated by Django 3.2.7 on 2021-11-17 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='nombre',
        ),
        migrations.AddField(
            model_name='comprador',
            name='dni',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 20, 16, 765533, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
