# Generated by Django 3.2.7 on 2021-10-10 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0002_auto_20211010_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 16, 2, 35, 723110, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
