# Generated by Django 3.2.7 on 2021-10-22 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FooGearApp', '0002_auto_20211018_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 18, 50, 35, 597541, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
