# Generated by Django 3.2.7 on 2021-11-17 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0002_auto_20211117_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprador',
            old_name='dni',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 26, 59, 256756, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
