# Generated by Django 3.2.7 on 2021-10-18 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0002_auto_20211018_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='clave',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 11, 51, 16, 352189, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
