# Generated by Django 3.2.7 on 2021-11-17 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0003_auto_20211117_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprador',
            old_name='nombre',
            new_name='dni',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 30, 34, 335845, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
