# Generated by Django 3.2.7 on 2021-10-11 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0003_alter_reserva_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 14, 5, 10, 631399, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
