# Generated by Django 3.2.7 on 2021-10-11 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0004_alter_reserva_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='clave_stock',
            field=models.CharField(default='e0001', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 41, 19, 931160, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
