# Generated by Django 3.2.7 on 2021-11-19 11:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FooGearApp', '0004_auto_20211117_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='comprador',
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 11, 25, 49, 672789, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
