# Generated by Django 3.2.7 on 2022-01-08 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0006_auto_20211123_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 12, 29, 21, 645524, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
