# Generated by Django 3.2.7 on 2022-01-08 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0007_alter_reserva_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='productos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 12, 30, 42, 795161, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
