# Generated by Django 3.2.7 on 2022-03-11 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FooGearApp', '0008_auto_20220108_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 19, 40, 19, 424192, tzinfo=utc), null=True, verbose_name='Fecha Reserva'),
        ),
    ]
